### PR TITLE
Adding MSAPI-MCAS and TrendMicro ServerProtect rules

### PR DESCRIPTION
**Pull request by wrharding**

### CODE REVIEW

**Comment by quadrantsec** [comment]
Minor issue with this PR. 

In rule set, it has:

``
alert any any any -> any any
``

In another rule set, it is:

``
alert any $EXTERNAL_NET any -> $HOME_NET any
``

I'd rather it keep with the spirt of the other signatures and use the variables.   If you can fix that,  i'll merge ASAP.  Thank you.

**Comment by wrharding** [comment]
@quadrantsec @beave Would you prefer a new PR or can this one be re-opened. Traffic direction has been added.

**Comment by quadrantsec** [comment]
Whatever works best for you
________________________________

**Comment by wrharding** [comment]
Re-opening this one would be best for continuity, imo.

**Comment by wrharding** [comment]
@quadrantsec can this PR be reopened? The updates are in place.

**Comment by quadrantsec** [comment]
Thank you sir!

**Pull request merged**
